"""Increased password hash length to 128

Revision ID: 14b7c9018651
Revises: 521477bf590d
Create Date: 2014-09-24 23:46:58.673490

"""

# revision identifiers, used by Alembic.
revision = '14b7c9018651'
down_revision = '521477bf590d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
