"""Increased password hash length to 128

Revision ID: 168f89710d2a
Revises: 14b7c9018651
Create Date: 2014-09-24 23:47:56.133119

"""

# revision identifiers, used by Alembic.
revision = '168f89710d2a'
down_revision = '14b7c9018651'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
