"""Increased length of email and changed name in holiday

Revision ID: 290322df8cdd
Revises: 3346cfe5d770
Create Date: 2014-09-26 05:33:20.632219

"""

# revision identifiers, used by Alembic.
revision = '290322df8cdd'
down_revision = '3346cfe5d770'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holiday', sa.Column('day', sa.String(length=10), nullable=True))
    op.drop_column('holiday', 'email')
    op.alter_column('user','user_email', type_=sa.String(length=50))
    op.alter_column('contact','email', type_=sa.String(length=50))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holiday', sa.Column('email', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('holiday', 'day')
    op.alter_column('user','user_email', type_=sa.String(length=20))
    op.alter_column('contact','email', type_=sa.String(length=20))
    ### end Alembic commands ###
