"""Made password not null

Revision ID: 2c5b36e34639
Revises: 168f89710d2a
Create Date: 2014-09-25 00:09:05.152406

"""

# revision identifiers, used by Alembic.
revision = '2c5b36e34639'
down_revision = '168f89710d2a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###
