"""Adding registered time for user and changed data type of start and end date in subscription

Revision ID: 3346cfe5d770
Revises: 2c5b36e34639
Create Date: 2014-09-26 04:57:49.826079

"""

# revision identifiers, used by Alembic.
revision = '3346cfe5d770'
down_revision = '2c5b36e34639'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.alter_column('subscription','start_date',type_=sa.DateTime())
    op.alter_column('subscription','end_date',type_=sa.DateTime())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_on')
    op.alter_column('subscription','start_date',type_=sa.BigInteger())
    op.alter_column('subscription','end_date',type_=sa.BigInteger())
    ### end Alembic commands ###
