"""Increased password hash length to 128

Revision ID: 521477bf590d
Revises: 846ab920e3
Create Date: 2014-09-24 23:35:55.761896

"""

# revision identifiers, used by Alembic.
revision = '521477bf590d'
down_revision = '846ab920e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
