"""Adding name field to user table

Revision ID: 5aeebedc790c
Revises: 361d0c4fafd3
Create Date: 2014-09-23 03:10:10.350264

"""

# revision identifiers, used by Alembic.
revision = '5aeebedc790c'
down_revision = '361d0c4fafd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
